#!/bin/sh

# Copyright 2018 herd-ui contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# shellcheck disable=SC2039
declare -a illegalPatterns=("\bOATS" "[^:</]datamgt[^:]" "[^/]Datamanagement[^/]" "nasd" "corp[^o]" "\btdate\b")

for illegalPattern in "${illegalPatterns[@]}"
do
    matchedLines=$(git diff --cached --diff-filter=AM --no-color | grep '^+' | grep -i "${illegalPattern}")
    if [ "$matchedLines" ]
    then
        echo 'Illegal pattern'
        echo "${illegalPattern}"
        echo 'found in:'
        echo "$matchedLines"
        exit 1
    fi

	 matchedAuthorInfo=$(git var GIT_AUTHOR_IDENT | grep -i "${illegalPattern}")
    if [ "$matchedAuthorInfo" ]
    then
        echo 'Illegal pattern'
        echo "${illegalPattern}"
        echo 'found in author info:'
        echo "$matchedAuthorInfo"
        exit 1
    fi
done
