#!/bin/sh

# Copyright 2018 herd-ui contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# secret-lint all selected files
echo "$FILES" | xargs ./../node_modules/.bin/secretlint
RET=$?
if [ $RET -eq 0 ] ;then
    exit 0
else
    printf "\n Commit did not pass secret-lint check. Aborting."
    exit 1
fi
